// This file is auto-generated by @hey-api/openapi-ts

export const AddressCreateSchema = {
    properties: {
        street_address: {
            type: 'string',
            maxLength: 255,
            title: 'Street Address'
        },
        apartment_suite: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Apartment Suite'
        },
        city: {
            type: 'string',
            maxLength: 128,
            title: 'City'
        },
        state: {
            type: 'string',
            maxLength: 128,
            title: 'State'
        },
        postal_code: {
            type: 'string',
            maxLength: 64,
            title: 'Postal Code'
        },
        country: {
            type: 'string',
            maxLength: 128,
            title: 'Country'
        },
        label: {
            '$ref': '#/components/schemas/AddressLabelEnum',
            default: 'home'
        },
        custom_label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Custom Label'
        },
        latitude: {
            type: 'number',
            title: 'Latitude'
        },
        longitude: {
            type: 'number',
            title: 'Longitude'
        },
        additional_notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Additional Notes'
        }
    },
    type: 'object',
    required: ['street_address', 'city', 'state', 'postal_code', 'country', 'latitude', 'longitude'],
    title: 'AddressCreate'
} as const;

export const AddressLabelEnumSchema = {
    type: 'string',
    enum: ['home', 'work', 'other', 'custom'],
    title: 'AddressLabelEnum'
} as const;

export const AddressPublicSchema = {
    properties: {
        street_address: {
            type: 'string',
            maxLength: 255,
            title: 'Street Address'
        },
        apartment_suite: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Apartment Suite'
        },
        city: {
            type: 'string',
            maxLength: 128,
            title: 'City'
        },
        state: {
            type: 'string',
            maxLength: 128,
            title: 'State'
        },
        postal_code: {
            type: 'string',
            maxLength: 64,
            title: 'Postal Code'
        },
        country: {
            type: 'string',
            maxLength: 128,
            title: 'Country'
        },
        label: {
            '$ref': '#/components/schemas/AddressLabelEnum',
            default: 'home'
        },
        custom_label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Custom Label'
        },
        latitude: {
            type: 'number',
            title: 'Latitude'
        },
        longitude: {
            type: 'number',
            title: 'Longitude'
        },
        additional_notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Additional Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: false
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['street_address', 'city', 'state', 'postal_code', 'country', 'latitude', 'longitude', 'id', 'created_at', 'updated_at'],
    title: 'AddressPublic'
} as const;

export const AddressUpdateSchema = {
    properties: {
        street_address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Street Address'
        },
        apartment_suite: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Apartment Suite'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        state: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128
                },
                {
                    type: 'null'
                }
            ],
            title: 'State'
        },
        postal_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Postal Code'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        label: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/AddressLabelEnum'
                },
                {
                    type: 'null'
                }
            ]
        },
        custom_label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Custom Label'
        },
        latitude: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latitude'
        },
        longitude: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Longitude'
        },
        additional_notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Additional Notes'
        }
    },
    additionalProperties: false,
    type: 'object',
    title: 'AddressUpdate'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_products_upload_product_imageSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_products-upload_product_image'
} as const;

export const BuyerTypeSchema = {
    type: 'string',
    enum: ['customer', 'retailer'],
    title: 'BuyerType'
} as const;

export const CategoryEnumSchema = {
    type: 'string',
    enum: ['electronics', 'clothing', 'food_beverage', 'home_garden', 'health_beauty', 'sports', 'toys', 'books', 'automotive', 'office_supplies', 'pet_supplies', 'jewellery', 'furniture'],
    title: 'CategoryEnum'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ImageReorderSchemaSchema = {
    properties: {
        images: {
            items: {
                '$ref': '#/components/schemas/ProductImageSchema'
            },
            type: 'array',
            title: 'Images'
        }
    },
    type: 'object',
    required: ['images'],
    title: 'ImageReorderSchema'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const OTPCreateSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'OTPCreate'
} as const;

export const OTPVerifySchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        code: {
            type: 'string',
            title: 'Code'
        }
    },
    type: 'object',
    required: ['email', 'code'],
    title: 'OTPVerify'
} as const;

export const ProductCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        category: {
            '$ref': '#/components/schemas/CategoryEnum'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        sku: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sku'
        },
        images: {
            items: {
                '$ref': '#/components/schemas/ProductImageSchema'
            },
            type: 'array',
            title: 'Images'
        },
        pricing_tiers: {
            items: {
                '$ref': '#/components/schemas/ProductPricingCreate'
            },
            type: 'array',
            minItems: 1,
            title: 'Pricing Tiers'
        },
        initial_stock: {
            type: 'integer',
            minimum: 0,
            title: 'Initial Stock',
            default: 0
        }
    },
    type: 'object',
    required: ['name', 'category', 'pricing_tiers'],
    title: 'ProductCreate'
} as const;

export const ProductImageSchemaSchema = {
    properties: {
        path: {
            type: 'string',
            title: 'Path'
        },
        order: {
            type: 'integer',
            title: 'Order'
        },
        is_primary: {
            type: 'boolean',
            title: 'Is Primary',
            default: false
        }
    },
    type: 'object',
    required: ['path', 'order'],
    title: 'ProductImageSchema'
} as const;

export const ProductInventoryPublicSchema = {
    properties: {
        stock_quantity: {
            type: 'integer',
            minimum: 0,
            title: 'Stock Quantity',
            default: 0
        },
        low_stock_threshold: {
            type: 'integer',
            minimum: 0,
            title: 'Low Stock Threshold',
            default: 10
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        last_restocked_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Restocked At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'product_id', 'last_restocked_at', 'created_at', 'updated_at'],
    title: 'ProductInventoryPublic'
} as const;

export const ProductInventoryUpdateSchema = {
    properties: {
        stock_quantity: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stock Quantity'
        },
        low_stock_threshold: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Low Stock Threshold'
        }
    },
    type: 'object',
    title: 'ProductInventoryUpdate'
} as const;

export const ProductPricingCreateSchema = {
    properties: {
        buyer_type: {
            '$ref': '#/components/schemas/BuyerType'
        },
        price: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                }
            ],
            title: 'Price'
        },
        min_quantity: {
            type: 'integer',
            minimum: 1,
            title: 'Min Quantity',
            default: 1
        },
        max_quantity: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Quantity'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['buyer_type', 'price'],
    title: 'ProductPricingCreate'
} as const;

export const ProductPricingPublicSchema = {
    properties: {
        buyer_type: {
            '$ref': '#/components/schemas/BuyerType'
        },
        price: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$',
            title: 'Price'
        },
        min_quantity: {
            type: 'integer',
            minimum: 1,
            title: 'Min Quantity',
            default: 1
        },
        max_quantity: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Quantity'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['buyer_type', 'price', 'id', 'product_id', 'created_at', 'updated_at'],
    title: 'ProductPricingPublic'
} as const;

export const ProductPricingUpdateSchema = {
    properties: {
        price: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price'
        },
        min_quantity: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Quantity'
        },
        max_quantity: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Quantity'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'ProductPricingUpdate'
} as const;

export const ProductPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        category: {
            '$ref': '#/components/schemas/CategoryEnum'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        seller_id: {
            type: 'string',
            format: 'uuid',
            title: 'Seller Id'
        },
        seller_type: {
            '$ref': '#/components/schemas/SellerType'
        },
        sku: {
            type: 'string',
            title: 'Sku'
        },
        images: {
            items: {
                '$ref': '#/components/schemas/ProductImageSchema'
            },
            type: 'array',
            title: 'Images'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        pricing_tiers: {
            items: {
                '$ref': '#/components/schemas/ProductPricingPublic'
            },
            type: 'array',
            title: 'Pricing Tiers',
            default: []
        },
        inventory: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProductInventoryPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        primary_image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Primary Image'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'category', 'id', 'seller_id', 'seller_type', 'sku', 'images', 'is_active', 'created_at', 'updated_at'],
    title: 'ProductPublic'
} as const;

export const ProductUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        category: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CategoryEnum'
                },
                {
                    type: 'null'
                }
            ]
        },
        tags: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        sku: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sku'
        },
        pricing_tier: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProductPricingUpdate'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'ProductUpdate'
} as const;

export const ProductsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProductPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProductsPublic'
} as const;

export const RoleAddSchema = {
    properties: {
        role: {
            '$ref': '#/components/schemas/RoleEnum'
        }
    },
    type: 'object',
    required: ['role'],
    title: 'RoleAdd',
    description: 'Request to add a role to user.'
} as const;

export const RoleEnumSchema = {
    type: 'string',
    enum: ['admin', 'customer', 'retailer', 'wholesaler', 'delivery_partner'],
    title: 'RoleEnum',
    description: 'Available user roles in the system.'
} as const;

export const RoleRemoveSchema = {
    properties: {
        role: {
            '$ref': '#/components/schemas/RoleEnum'
        }
    },
    type: 'object',
    required: ['role'],
    title: 'RoleRemove',
    description: 'Request to remove a role from user.'
} as const;

export const RoleSwitchSchema = {
    properties: {
        role: {
            '$ref': '#/components/schemas/RoleEnum'
        }
    },
    type: 'object',
    required: ['role'],
    title: 'RoleSwitch',
    description: 'Request to switch active role.'
} as const;

export const SellerTypeSchema = {
    type: 'string',
    enum: ['retailer', 'wholesaler'],
    title: 'SellerType'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        roles: {
            items: {
                '$ref': '#/components/schemas/RoleEnum'
            },
            type: 'array',
            title: 'Roles'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        roles: {
            items: {
                '$ref': '#/components/schemas/RoleEnum'
            },
            type: 'array',
            title: 'Roles',
            default: []
        },
        active_role: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/RoleEnum'
                },
                {
                    type: 'null'
                }
            ]
        },
        active_address_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Active Address Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['email', 'id', 'created_at', 'updated_at'],
    title: 'UserPublic'
} as const;

export const UserPublicWithTokenSchema = {
    properties: {
        user: {
            '$ref': '#/components/schemas/UserPublic'
        },
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['user', 'access_token'],
    title: 'UserPublicWithToken'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        roles: {
            items: {
                '$ref': '#/components/schemas/RoleEnum'
            },
            type: 'array',
            minItems: 1,
            title: 'Roles'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;