// This file is auto-generated by @hey-api/openapi-ts

export type AddressCreate = {
    street_address: string;
    apartment_suite?: (string | null);
    city: string;
    state: string;
    postal_code: string;
    country: string;
    label?: AddressLabelEnum;
    custom_label?: (string | null);
    latitude: number;
    longitude: number;
    additional_notes?: (string | null);
};

export type AddressLabelEnum = 'home' | 'work' | 'other' | 'custom';

export type AddressPublic = {
    street_address: string;
    apartment_suite?: (string | null);
    city: string;
    state: string;
    postal_code: string;
    country: string;
    label?: AddressLabelEnum;
    custom_label?: (string | null);
    latitude: number;
    longitude: number;
    additional_notes?: (string | null);
    id: string;
    is_active?: boolean;
    created_at: string;
    updated_at: string;
};

export type AddressUpdate = {
    street_address?: (string | null);
    apartment_suite?: (string | null);
    city?: (string | null);
    state?: (string | null);
    postal_code?: (string | null);
    country?: (string | null);
    label?: (AddressLabelEnum | null);
    custom_label?: (string | null);
    latitude?: (number | null);
    longitude?: (number | null);
    additional_notes?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_products_upload_product_image = {
    file: (Blob | File);
};

export type BuyerType = 'customer' | 'retailer';

export type CategoryEnum = 'electronics' | 'clothing' | 'food_beverage' | 'home_garden' | 'health_beauty' | 'sports' | 'toys' | 'books' | 'automotive' | 'office_supplies' | 'pet_supplies' | 'jewellery' | 'furniture';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ImageReorderSchema = {
    images: Array<ProductImageSchema>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OTPCreate = {
    email: string;
};

export type OTPVerify = {
    email: string;
    code: string;
};

export type ProductCreate = {
    name: string;
    description?: (string | null);
    category: CategoryEnum;
    tags?: Array<(string)>;
    brand?: (string | null);
    sku?: (string | null);
    images?: Array<ProductImageSchema>;
    pricing_tiers: Array<ProductPricingCreate>;
    initial_stock?: number;
    address_id?: (string | null);
};

export type ProductImageSchema = {
    path: string;
    order: number;
    is_primary?: boolean;
};

export type ProductInventoryPublic = {
    stock_quantity?: number;
    low_stock_threshold?: number;
    id: string;
    product_id: string;
    last_restocked_at: (string | null);
    created_at: string;
    updated_at: string;
};

export type ProductInventoryUpdate = {
    stock_quantity?: (number | null);
    low_stock_threshold?: (number | null);
};

export type ProductPricingCreate = {
    buyer_type: BuyerType;
    price: (number | string);
    min_quantity?: number;
    max_quantity?: (number | null);
    is_active?: boolean;
};

export type ProductPricingPublic = {
    buyer_type: BuyerType;
    price: string;
    min_quantity?: number;
    max_quantity?: (number | null);
    is_active?: boolean;
    id: string;
    product_id: string;
    created_at: string;
    updated_at: string;
};

export type ProductPricingUpdate = {
    price?: (number | string | null);
    min_quantity?: (number | null);
    max_quantity?: (number | null);
    is_active?: (boolean | null);
};

export type ProductPublic = {
    name: string;
    description?: (string | null);
    category: CategoryEnum;
    tags?: Array<(string)>;
    brand?: (string | null);
    id: string;
    seller_id: string;
    seller_type: SellerType;
    sku: string;
    images: Array<ProductImageSchema>;
    is_active: boolean;
    pricing_tiers?: Array<ProductPricingPublic>;
    inventory?: (ProductInventoryPublic | null);
    primary_image?: (string | null);
    address_id?: (string | null);
    distance_km?: (number | null);
    created_at: string;
    updated_at: string;
};

export type ProductsPublic = {
    data: Array<ProductPublic>;
    count: number;
};

export type ProductUpdate = {
    name?: (string | null);
    description?: (string | null);
    category?: (CategoryEnum | null);
    tags?: (Array<(string)> | null);
    is_active?: (boolean | null);
    sku?: (string | null);
    pricing_tier?: (ProductPricingUpdate | null);
    brand?: (string | null);
    address_id?: (string | null);
};

/**
 * Request to add a role to user.
 */
export type RoleAdd = {
    role: RoleEnum;
};

/**
 * Available user roles in the system.
 */
export type RoleEnum = 'admin' | 'customer' | 'retailer' | 'wholesaler' | 'delivery_partner';

/**
 * Request to remove a role from user.
 */
export type RoleRemove = {
    role: RoleEnum;
};

/**
 * Request to switch active role.
 */
export type RoleSwitch = {
    role: RoleEnum;
};

export type SellerType = 'retailer' | 'wholesaler';

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    full_name?: (string | null);
    password: string;
    roles?: Array<RoleEnum>;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    full_name?: (string | null);
    id: string;
    roles?: Array<RoleEnum>;
    active_role?: (RoleEnum | null);
    active_address_id?: (string | null);
    created_at: string;
    updated_at: string;
};

export type UserPublicWithToken = {
    user: UserPublic;
    access_token: string;
    token_type?: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
    roles?: Array<RoleEnum>;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AddressesListAddressesResponse = (Array<AddressPublic>);

export type AddressesCreateAddressData = {
    requestBody: AddressCreate;
};

export type AddressesCreateAddressResponse = (AddressPublic);

export type AddressesUpdateAddressData = {
    addressId: string;
    requestBody: AddressUpdate;
};

export type AddressesUpdateAddressResponse = (AddressPublic);

export type AddressesDeleteAddressData = {
    addressId: string;
};

export type AddressesDeleteAddressResponse = (void);

export type AddressesSetActiveAddressData = {
    addressId: string;
};

export type AddressesSetActiveAddressResponse = (AddressPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginLoginWithGoogleResponse = (unknown);

export type LoginLoginWithGoogleCallbackResponse = (unknown);

export type LoginRequestLoginOtpData = {
    requestBody: OTPCreate;
};

export type LoginRequestLoginOtpResponse = (Message);

export type LoginVerifyLoginOtpData = {
    requestBody: OTPVerify;
};

export type LoginVerifyLoginOtpResponse = (Token);

export type ProductsListProductsData = {
    brands?: (string | null);
    category?: (CategoryEnum | null);
    inStockOnly?: (boolean | null);
    isActive?: boolean;
    latitude?: (number | null);
    limit?: number;
    longitude?: (number | null);
    maxPrice?: (number | string | null);
    minPrice?: (number | string | null);
    radiusKm?: (number | null);
    search?: (string | null);
    sellerId?: (string | null);
    sellerType?: (SellerType | null);
    skip?: number;
    sortBy?: ('newest' | 'price_asc' | 'price_desc' | 'distance_asc' | null);
    tags?: (string | null);
};

export type ProductsListProductsResponse = (ProductsPublic);

export type ProductsCreateProductData = {
    requestBody: ProductCreate;
};

export type ProductsCreateProductResponse = (ProductPublic);

export type ProductsAutocompleteProductsData = {
    category?: (CategoryEnum | null);
    isActive?: boolean;
    limit?: number;
    q: string;
    sellerType?: (SellerType | null);
};

export type ProductsAutocompleteProductsResponse = (Array<(string)>);

export type ProductsGetProductData = {
    productId: string;
};

export type ProductsGetProductResponse = (ProductPublic);

export type ProductsUpdateProductData = {
    productId: string;
    requestBody: ProductUpdate;
};

export type ProductsUpdateProductResponse = (ProductPublic);

export type ProductsDeleteProductData = {
    productId: string;
};

export type ProductsDeleteProductResponse = (Message);

export type ProductsUpdateProductInventoryData = {
    productId: string;
    requestBody: ProductInventoryUpdate;
};

export type ProductsUpdateProductInventoryResponse = (ProductInventoryPublic);

export type ProductsUploadProductImageData = {
    formData: Body_products_upload_product_image;
    productId: string;
};

export type ProductsUploadProductImageResponse = (ProductPublic);

export type ProductsDeleteProductImageData = {
    imagePath: string;
    productId: string;
};

export type ProductsDeleteProductImageResponse = (ProductPublic);

export type ProductsReorderProductImagesData = {
    productId: string;
    requestBody: ImageReorderSchema;
};

export type ProductsReorderProductImagesResponse = (ProductPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UsersGetUserRolesResponse = (Array<RoleEnum>);

export type UsersAddUserRoleData = {
    requestBody: RoleAdd;
};

export type UsersAddUserRoleResponse = (UserPublic);

export type UsersRemoveUserRoleData = {
    requestBody: RoleRemove;
};

export type UsersRemoveUserRoleResponse = (UserPublic);

export type UsersSwitchUserRoleData = {
    requestBody: RoleSwitch;
};

export type UsersSwitchUserRoleResponse = (UserPublic);

export type UsersSignupRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersSignupRegisterUserResponse = (UserPublicWithToken);

export type UsersSignupVerifyEmailData = {
    requestBody: OTPVerify;
};

export type UsersSignupVerifyEmailResponse = (Message);

export type UsersSignupResendVerificationOtpResponse = (Message);

export type UtilsHealthResponse = (boolean);