from .addresses import (
    create_address,
    delete_address,
    get_address_for_user,
    get_addresses_for_user,
    set_active_address,
    update_address,
)
from .cart import (
    add_to_cart,
    clear_cart,
    get_cart_with_items,
    get_or_create_cart,
    remove_from_cart,
    update_cart_item_quantity,
)
from .orders import (
    create_orders_from_cart,
    create_unified_payment_for_orders,
    get_available_delivery_orders,
    get_order_by_id,
    get_orders_for_buyer,
    get_orders_for_delivery_partner,
    get_orders_for_seller,
    update_order_status,
)
from .otp import create_otp, verify_otp
from .products import (
    autocomplete_products,
    create_product,
    delete_product,
    get_address_coords,
    get_product_by_id,
    get_product_by_seller_and_sku,
    get_products,
    get_users_active_address_coords,
    update_inventory,
    update_pricing_tier,
    update_product,
    update_product_images,
)
from .users import (
    add_role_to_user,
    authenticate,
    create_user,
    get_user_by_email,
    remove_role_from_user,
    switch_active_role,
    update_user,
)

__all__ = [
    "create_user",
    "update_user",
    "get_user_by_email",
    "authenticate",
    "add_role_to_user",
    "remove_role_from_user",
    "switch_active_role",
    "create_address",
    "update_address",
    "delete_address",
    "get_addresses_for_user",
    "get_address_for_user",
    "set_active_address",
    "get_or_create_cart",
    "get_cart_with_items",
    "add_to_cart",
    "update_cart_item_quantity",
    "remove_from_cart",
    "clear_cart",
    "create_otp",
    "verify_otp",
    "create_product",
    "get_products",
    "get_product_by_id",
    "get_product_by_seller_and_sku",
    "update_product",
    "update_inventory",
    "delete_product",
    "update_product_images",
    "update_pricing_tier",
    "get_address_coords",
    "autocomplete_products",
    "get_users_active_address_coords",
]
