"""product brand + address_id, search filters

Revision ID: d3abac394ad9
Revises: 1d6de7e98935
Create Date: 2025-11-19 14:04:11.188129

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd3abac394ad9'
down_revision = '1d6de7e98935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('product', sa.Column('address_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_product_address_id'), 'product', ['address_id'], unique=False)
    op.create_index(op.f('ix_product_brand'), 'product', ['brand'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_brand'), table_name='product')
    op.drop_index(op.f('ix_product_address_id'), table_name='product')
    op.drop_column('product', 'address_id')
    op.drop_column('product', 'brand')
    # ### end Alembic commands ###
