"""coupons and settlements

Revision ID: 2d6803cf3858
Revises: 2f0c368be21b
Create Date: 2025-11-22 14:16:21.218448

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d6803cf3858'
down_revision = '2f0c368be21b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FIXED', name='discounttype'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_order_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('target_emails', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_code'), 'coupon', ['code'], unique=True)
    op.create_index(op.f('ix_coupon_is_active'), 'coupon', ['is_active'], unique=False)
    op.create_index(op.f('ix_coupon_is_featured'), 'coupon', ['is_featured'], unique=False)
    op.create_table('paymentsettlement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('user_type', sa.Enum('SELLER', 'DELIVERY_PARTNER', name='usertype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('settlement_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='settlementstatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('order_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paymentsettlement_settlement_date'), 'paymentsettlement', ['settlement_date'], unique=False)
    op.create_index(op.f('ix_paymentsettlement_status'), 'paymentsettlement', ['status'], unique=False)
    op.create_index(op.f('ix_paymentsettlement_user_id'), 'paymentsettlement', ['user_id'], unique=False)
    op.create_index(op.f('ix_paymentsettlement_user_type'), 'paymentsettlement', ['user_type'], unique=False)
    op.create_table('paymentcoupon',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('coupon_id', sa.Uuid(), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paymentcoupon_coupon_id'), 'paymentcoupon', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_paymentcoupon_payment_id'), 'paymentcoupon', ['payment_id'], unique=False)

    op.add_column('order', sa.Column('original_subtotal', sa.Numeric(precision=10, scale=2), nullable=True))
    op.execute('UPDATE "order" SET original_subtotal = order_subtotal WHERE original_subtotal IS NULL')
    op.alter_column('order', 'original_subtotal', nullable=False)

    op.add_column('order', sa.Column('settlement_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_order_settlement_id'), 'order', ['settlement_id'], unique=False)
    op.create_foreign_key(None, 'order', 'paymentsettlement', ['settlement_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_index(op.f('ix_order_settlement_id'), table_name='order')
    op.drop_column('order', 'settlement_id')
    op.drop_column('order', 'original_subtotal')
    op.drop_index(op.f('ix_paymentcoupon_payment_id'), table_name='paymentcoupon')
    op.drop_index(op.f('ix_paymentcoupon_coupon_id'), table_name='paymentcoupon')
    op.drop_table('paymentcoupon')
    op.drop_index(op.f('ix_paymentsettlement_user_type'), table_name='paymentsettlement')
    op.drop_index(op.f('ix_paymentsettlement_user_id'), table_name='paymentsettlement')
    op.drop_index(op.f('ix_paymentsettlement_status'), table_name='paymentsettlement')
    op.drop_index(op.f('ix_paymentsettlement_settlement_date'), table_name='paymentsettlement')
    op.drop_table('paymentsettlement')
    op.drop_index(op.f('ix_coupon_is_featured'), table_name='coupon')
    op.drop_index(op.f('ix_coupon_is_active'), table_name='coupon')
    op.drop_index(op.f('ix_coupon_code'), table_name='coupon')
    op.drop_table('coupon')
    # ### end Alembic commands ###
