"""addresses

Revision ID: ab554e254ead
Revises: 2aa045dc9576
Create Date: 2025-11-17 06:34:55.992079

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ab554e254ead'
down_revision = '2aa045dc9576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create address table without the foreign key constraint first
    op.create_table('address',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('street_address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('apartment_suite', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('label', sa.Enum('HOME', 'WORK', 'OTHER', 'CUSTOM', name='addresslabelenum'), nullable=False),
    sa.Column('custom_label', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('additional_notes', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_label'), 'address', ['label'], unique=False)
    op.create_index(op.f('ix_address_user_id'), 'address', ['user_id'], unique=False)

    # Add user.active_address_id column
    op.add_column('user', sa.Column('active_address_id', sa.Uuid(), nullable=True))

    # Now add the foreign key constraints
    op.create_foreign_key('fk_address_user_id', 'address', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_user_active_address_id', 'user', 'address', ['active_address_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraints first
    op.drop_constraint('fk_user_active_address_id', 'user', type_='foreignkey')
    op.drop_constraint('fk_address_user_id', 'address', type_='foreignkey')

    # Drop user column
    op.drop_column('user', 'active_address_id')

    # Drop address table
    op.drop_index(op.f('ix_address_user_id'), table_name='address')
    op.drop_index(op.f('ix_address_label'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
