"""otp

Revision ID: 2aa045dc9576
Revises: 9c93298c9e26
Create Date: 2025-11-12 16:38:53.495459

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2aa045dc9576'
down_revision = '9c93298c9e26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.Column('purpose', sa.Enum('EMAIL_VERIFICATION', 'LOGIN', name='otppurpose'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_code'), 'otp', ['code'], unique=False)
    op.create_index(op.f('ix_otp_expires_at'), 'otp', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_is_used'), 'otp', ['is_used'], unique=False)
    op.create_index(op.f('ix_otp_purpose'), 'otp', ['purpose'], unique=False)
    op.create_index(op.f('ix_otp_user_id'), 'otp', ['user_id'], unique=False)
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_verified')
    op.drop_index(op.f('ix_otp_user_id'), table_name='otp')
    op.drop_index(op.f('ix_otp_purpose'), table_name='otp')
    op.drop_index(op.f('ix_otp_is_used'), table_name='otp')
    op.drop_index(op.f('ix_otp_expires_at'), table_name='otp')
    op.drop_index(op.f('ix_otp_code'), table_name='otp')
    op.drop_table('otp')
    # ### end Alembic commands ###
