/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelectRoleRouteImport } from './routes/select-role'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutCheckoutRouteImport } from './routes/_layout/checkout'
import { Route as LayoutCartRouteImport } from './routes/_layout/cart'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutSellIndexRouteImport } from './routes/_layout/sell/index'
import { Route as LayoutBuyIndexRouteImport } from './routes/_layout/buy/index'
import { Route as OauthGoogleCallbackRouteImport } from './routes/oauth.google.callback'
import { Route as LayoutSellerOrdersRouteImport } from './routes/_layout/seller/orders'
import { Route as LayoutSellNewRouteImport } from './routes/_layout/sell/new'
import { Route as LayoutSellBulkRouteImport } from './routes/_layout/sell/bulk'
import { Route as LayoutSellProductIdRouteImport } from './routes/_layout/sell/$productId'
import { Route as LayoutOrdersMeRouteImport } from './routes/_layout/orders/me'
import { Route as LayoutOrdersOrderIdRouteImport } from './routes/_layout/orders/$orderId'
import { Route as LayoutDeliveryMineRouteImport } from './routes/_layout/delivery/mine'
import { Route as LayoutDeliveryAvailableRouteImport } from './routes/_layout/delivery/available'
import { Route as LayoutBuyProductIdRouteImport } from './routes/_layout/buy/$productId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoleRoute = SelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCheckoutRoute = LayoutCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCartRoute = LayoutCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSellIndexRoute = LayoutSellIndexRouteImport.update({
  id: '/sell/',
  path: '/sell/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBuyIndexRoute = LayoutBuyIndexRouteImport.update({
  id: '/buy/',
  path: '/buy/',
  getParentRoute: () => LayoutRoute,
} as any)
const OauthGoogleCallbackRoute = OauthGoogleCallbackRouteImport.update({
  id: '/oauth/google/callback',
  path: '/oauth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSellerOrdersRoute = LayoutSellerOrdersRouteImport.update({
  id: '/seller/orders',
  path: '/seller/orders',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSellNewRoute = LayoutSellNewRouteImport.update({
  id: '/sell/new',
  path: '/sell/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSellBulkRoute = LayoutSellBulkRouteImport.update({
  id: '/sell/bulk',
  path: '/sell/bulk',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSellProductIdRoute = LayoutSellProductIdRouteImport.update({
  id: '/sell/$productId',
  path: '/sell/$productId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrdersMeRoute = LayoutOrdersMeRouteImport.update({
  id: '/orders/me',
  path: '/orders/me',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrdersOrderIdRoute = LayoutOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDeliveryMineRoute = LayoutDeliveryMineRouteImport.update({
  id: '/delivery/mine',
  path: '/delivery/mine',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDeliveryAvailableRoute = LayoutDeliveryAvailableRouteImport.update({
  id: '/delivery/available',
  path: '/delivery/available',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBuyProductIdRoute = LayoutBuyProductIdRouteImport.update({
  id: '/buy/$productId',
  path: '/buy/$productId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-role': typeof SelectRoleRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof LayoutAdminRoute
  '/cart': typeof LayoutCartRoute
  '/checkout': typeof LayoutCheckoutRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/buy/$productId': typeof LayoutBuyProductIdRoute
  '/delivery/available': typeof LayoutDeliveryAvailableRoute
  '/delivery/mine': typeof LayoutDeliveryMineRoute
  '/orders/$orderId': typeof LayoutOrdersOrderIdRoute
  '/orders/me': typeof LayoutOrdersMeRoute
  '/sell/$productId': typeof LayoutSellProductIdRoute
  '/sell/bulk': typeof LayoutSellBulkRoute
  '/sell/new': typeof LayoutSellNewRoute
  '/seller/orders': typeof LayoutSellerOrdersRoute
  '/oauth/google/callback': typeof OauthGoogleCallbackRoute
  '/buy': typeof LayoutBuyIndexRoute
  '/sell': typeof LayoutSellIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-role': typeof SelectRoleRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof LayoutAdminRoute
  '/cart': typeof LayoutCartRoute
  '/checkout': typeof LayoutCheckoutRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/buy/$productId': typeof LayoutBuyProductIdRoute
  '/delivery/available': typeof LayoutDeliveryAvailableRoute
  '/delivery/mine': typeof LayoutDeliveryMineRoute
  '/orders/$orderId': typeof LayoutOrdersOrderIdRoute
  '/orders/me': typeof LayoutOrdersMeRoute
  '/sell/$productId': typeof LayoutSellProductIdRoute
  '/sell/bulk': typeof LayoutSellBulkRoute
  '/sell/new': typeof LayoutSellNewRoute
  '/seller/orders': typeof LayoutSellerOrdersRoute
  '/oauth/google/callback': typeof OauthGoogleCallbackRoute
  '/buy': typeof LayoutBuyIndexRoute
  '/sell': typeof LayoutSellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-role': typeof SelectRoleRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/cart': typeof LayoutCartRoute
  '/_layout/checkout': typeof LayoutCheckoutRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/buy/$productId': typeof LayoutBuyProductIdRoute
  '/_layout/delivery/available': typeof LayoutDeliveryAvailableRoute
  '/_layout/delivery/mine': typeof LayoutDeliveryMineRoute
  '/_layout/orders/$orderId': typeof LayoutOrdersOrderIdRoute
  '/_layout/orders/me': typeof LayoutOrdersMeRoute
  '/_layout/sell/$productId': typeof LayoutSellProductIdRoute
  '/_layout/sell/bulk': typeof LayoutSellBulkRoute
  '/_layout/sell/new': typeof LayoutSellNewRoute
  '/_layout/seller/orders': typeof LayoutSellerOrdersRoute
  '/oauth/google/callback': typeof OauthGoogleCallbackRoute
  '/_layout/buy/': typeof LayoutBuyIndexRoute
  '/_layout/sell/': typeof LayoutSellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/select-role'
    | '/signup'
    | '/verify-email'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/settings'
    | '/'
    | '/buy/$productId'
    | '/delivery/available'
    | '/delivery/mine'
    | '/orders/$orderId'
    | '/orders/me'
    | '/sell/$productId'
    | '/sell/bulk'
    | '/sell/new'
    | '/seller/orders'
    | '/oauth/google/callback'
    | '/buy'
    | '/sell'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/select-role'
    | '/signup'
    | '/verify-email'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/settings'
    | '/'
    | '/buy/$productId'
    | '/delivery/available'
    | '/delivery/mine'
    | '/orders/$orderId'
    | '/orders/me'
    | '/sell/$productId'
    | '/sell/bulk'
    | '/sell/new'
    | '/seller/orders'
    | '/oauth/google/callback'
    | '/buy'
    | '/sell'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/select-role'
    | '/signup'
    | '/verify-email'
    | '/_layout/admin'
    | '/_layout/cart'
    | '/_layout/checkout'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/buy/$productId'
    | '/_layout/delivery/available'
    | '/_layout/delivery/mine'
    | '/_layout/orders/$orderId'
    | '/_layout/orders/me'
    | '/_layout/sell/$productId'
    | '/_layout/sell/bulk'
    | '/_layout/sell/new'
    | '/_layout/seller/orders'
    | '/oauth/google/callback'
    | '/_layout/buy/'
    | '/_layout/sell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SelectRoleRoute: typeof SelectRoleRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  OauthGoogleCallbackRoute: typeof OauthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-role': {
      id: '/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof SelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/checkout': {
      id: '/_layout/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof LayoutCheckoutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cart': {
      id: '/_layout/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof LayoutCartRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sell/': {
      id: '/_layout/sell/'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof LayoutSellIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/buy/': {
      id: '/_layout/buy/'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof LayoutBuyIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/oauth/google/callback': {
      id: '/oauth/google/callback'
      path: '/oauth/google/callback'
      fullPath: '/oauth/google/callback'
      preLoaderRoute: typeof OauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/seller/orders': {
      id: '/_layout/seller/orders'
      path: '/seller/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof LayoutSellerOrdersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sell/new': {
      id: '/_layout/sell/new'
      path: '/sell/new'
      fullPath: '/sell/new'
      preLoaderRoute: typeof LayoutSellNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sell/bulk': {
      id: '/_layout/sell/bulk'
      path: '/sell/bulk'
      fullPath: '/sell/bulk'
      preLoaderRoute: typeof LayoutSellBulkRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sell/$productId': {
      id: '/_layout/sell/$productId'
      path: '/sell/$productId'
      fullPath: '/sell/$productId'
      preLoaderRoute: typeof LayoutSellProductIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orders/me': {
      id: '/_layout/orders/me'
      path: '/orders/me'
      fullPath: '/orders/me'
      preLoaderRoute: typeof LayoutOrdersMeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orders/$orderId': {
      id: '/_layout/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof LayoutOrdersOrderIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/delivery/mine': {
      id: '/_layout/delivery/mine'
      path: '/delivery/mine'
      fullPath: '/delivery/mine'
      preLoaderRoute: typeof LayoutDeliveryMineRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/delivery/available': {
      id: '/_layout/delivery/available'
      path: '/delivery/available'
      fullPath: '/delivery/available'
      preLoaderRoute: typeof LayoutDeliveryAvailableRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/buy/$productId': {
      id: '/_layout/buy/$productId'
      path: '/buy/$productId'
      fullPath: '/buy/$productId'
      preLoaderRoute: typeof LayoutBuyProductIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutCartRoute: typeof LayoutCartRoute
  LayoutCheckoutRoute: typeof LayoutCheckoutRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutBuyProductIdRoute: typeof LayoutBuyProductIdRoute
  LayoutDeliveryAvailableRoute: typeof LayoutDeliveryAvailableRoute
  LayoutDeliveryMineRoute: typeof LayoutDeliveryMineRoute
  LayoutOrdersOrderIdRoute: typeof LayoutOrdersOrderIdRoute
  LayoutOrdersMeRoute: typeof LayoutOrdersMeRoute
  LayoutSellProductIdRoute: typeof LayoutSellProductIdRoute
  LayoutSellBulkRoute: typeof LayoutSellBulkRoute
  LayoutSellNewRoute: typeof LayoutSellNewRoute
  LayoutSellerOrdersRoute: typeof LayoutSellerOrdersRoute
  LayoutBuyIndexRoute: typeof LayoutBuyIndexRoute
  LayoutSellIndexRoute: typeof LayoutSellIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutCartRoute: LayoutCartRoute,
  LayoutCheckoutRoute: LayoutCheckoutRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutBuyProductIdRoute: LayoutBuyProductIdRoute,
  LayoutDeliveryAvailableRoute: LayoutDeliveryAvailableRoute,
  LayoutDeliveryMineRoute: LayoutDeliveryMineRoute,
  LayoutOrdersOrderIdRoute: LayoutOrdersOrderIdRoute,
  LayoutOrdersMeRoute: LayoutOrdersMeRoute,
  LayoutSellProductIdRoute: LayoutSellProductIdRoute,
  LayoutSellBulkRoute: LayoutSellBulkRoute,
  LayoutSellNewRoute: LayoutSellNewRoute,
  LayoutSellerOrdersRoute: LayoutSellerOrdersRoute,
  LayoutBuyIndexRoute: LayoutBuyIndexRoute,
  LayoutSellIndexRoute: LayoutSellIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SelectRoleRoute: SelectRoleRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  OauthGoogleCallbackRoute: OauthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
